#########################################################################
# Title:         Cloudbox: NZBGet - Settings Task                       #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Stop Container
- name: Settings | Wait for nzbget.conf to be created
  wait_for:
    path: "/opt/nzbget/nzbget.conf"
    state: present

- name: Settings | Stop container to customize nzbget.conf
  docker_container:
    name: nzbget
    state: stopped

# Authentication
- name: Settings | Set Username
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^ControlUsername\s?='
    line: "ControlUsername={{ user.name }}"
    state: present

- name: Settings | Set Password
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^ControlPassword\s?=.*'
    line: "ControlPassword={{ user.pass }}"
    state: present

- name: Settings | Set FormAuth
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^FormAuth\s?=.*'
    line: 'FormAuth=yes'
    state: present

# Paths
- name: Settings | Change MainDir to downloads directory
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^MainDir\s?='
    line: 'MainDir=/downloads/nzbs/nzbget'
    state: present

- name: Settings | Change QueueDir path
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^QueueDir\s?='
    line: 'QueueDir=${MainDir}/queue'
    state: present

- name: Settings | Change TempDir path
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^TempDir\s?='
    line: 'TempDir=${MainDir}/tmp'
    state: present

- name: Settings | Change ScriptDir path
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^ScriptDir\s?='
    line: 'ScriptDir=/scripts/nzbget'
    state: present

- name: Settings | Change LockFile path
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^LockFile\s?='
    line: 'LockFile=/config/nzbget.lock'
    state: present

- name: Settings | Change LogFile path
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^LogFile\s?='
    line: 'LogFile=${MainDir}/nzbget.log'
    state: present

# Categories

- name: Settings | Rename movies category
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^Category1\.Name\s?=.*'
    line: 'Category1.Name=movies'
    state: present

- name: Settings | Add aliases to movies category
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^Category1\.Aliases\s?='
    line: 'Category1.Aliases=movies*, Movies*'
    state: present

- name: Settings | Rename series category
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^Category2\.Name\s?=.*'
    line: 'Category2.Name=series'
    state: present

- name: Settings | Add aliases to series category
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^Category2\.Aliases\s?='
    line: 'Category2.Aliases=TV - HD, TV - SD, TV*'
    state: present

- name: Settings | Rename music category
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^Category3\.Name\s?=.*'
    line: 'Category3.Name=music'
    state: present

- name: Settings | Add aliases to music category
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^Category3\.Aliases\s?='
    line: 'Category3.Aliases=audio*'
    state: present

- name: Settings | Rename apps category
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^Category4\.Name\s?=.*'
    line: 'Category4.Name=apps'
    state: present

- name: Settings | Add aliases to apps category
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^Category4\.Aliases\s?='
    line: 'Category4.Aliases=apps*, pc*'
    state: present

- name: Settings | Add Radarr category
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^Category5\.Name\s?='
    line: 'Category5.Name=radarr'
    state: present

- name: Settings | Add Sonarr category
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^Category6\.Name\s?='
    line: 'Category6.Name=sonarr'
    state: present

- name: Settings | Add Lidarr category
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^Category7\.Name\s?='
    line: 'Category7.Name=lidarr'
    state: present

# Miscellaneous
- name: Settings | Set ShellOverride
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^ShellOverride\s?=.*'
    line: 'ShellOverride=.py=/usr/bin/python3'
    state: present

- name: Settings | Set DiskSpace
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^DiskSpace\s?=.*'
    line: 'DiskSpace=100000'
    state: present

- name: Settings | Remove 'Task1' schedule
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: "{{ item.regexp }}"
    state: absent
  with_items:
    - {regexp: '.Task1\.Time\=.*' }
    - {regexp: '.Task1\.WeekDays\=.*' }
    - {regexp: '.Task1\.Command\=.*' }
    - {regexp: '.Task1\.Param\=.*' }

- name: Settings | Create a'Tasks1' unpauser schedule
  blockinfile:
    path: "/opt/nzbget/nzbget.conf"
    block: |
      Task1.Time=*,*:00,*:15,*:30,*:45
      Task1.WeekDays=1-7
      Task1.Command=UnpauseDownload
      Task1.Param=
    insertafter: "^### SCHEDULER"

- name: Settings | Set HealthCheck
  lineinfile:
    path: "/opt/nzbget/nzbget.conf"
    regexp: '^HealthCheck\s?=.*'
    line: 'HealthCheck=Delete'
    state: present

# Start Container
- name: Settings | Start container to apply changes
  docker_container:
    name: nzbget
    state: started
