#########################################################################
# Title:         Cloudbox: Organizr Role                                #
# Author(s):     l3uddz, desimaniac, jonfinley                          #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  organizr/organizr                                      #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: organizr
  when: (cloudflare_enabled) and not (organizr.direct_domain|default(false,true))

- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: "{{ item }}"
  with_items:
    - "{{ user.domain }}"
    - "www"
  when: (cloudflare_enabled) and (organizr.direct_domain|default(false,true))

- name: Stop and remove any existing container
  docker_container:
    name: organizr
    state: absent

# START - Migration Tasks
- name: Check if previous organizr exists
  stat:
    path: "/opt/organizr/www/Dashboard/functions.php"
  register: function_php

- name: Get version of previous organizr
  shell: cat /opt/organizr/www/Dashboard/functions.php | grep "define('INSTALLEDVERSION'" | awk '{ print $2 }' | sed -n "s/^.*'\(.*\)'.*$/\1/ p"
  register: organizr_version
  when: function_php.stat.exists

- name: Move older version 'organizr' to 'organizrv1'
  shell: |
    mv /opt/organizr /opt/organizrv1
    chown -R {{ user.name }}:{{ user.name }} /opt/organizrv1
  when: (function_php.stat.exists) and (organizr_version.stdout is version('2.0', '<'))
# END - Migration Tasks

- name: Remove certain js files from organizr
  file: "path=/opt/organizr/www/Dashboard/js/{{ item }} state=absent"
  with_items:
    - "custom.min.js"
    - "functions.js"
  ignore_errors: yes

- name: Create Organizr directories
  file: "path={{ item }} state=directory owner={{ user.name }} group={{ user.name }} mode=0775"
  with_items:
    - /opt/organizr

- name: Create and start container
  docker_container:
    name: organizr
    image: "organizr/organizr"
    pull: yes
    env:
      fpm: "{{ (organizr.fpm|default(false,true)) }}"
      branch: "{{ (organizr.branch|default(false,true)) }}"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "{{ (organizr.direct_domain|default(false,true)) | ternary(user.domain + ',' + 'www.' + user.domain,'organizr.' + user.domain) }}"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "{{ (organizr.direct_domain|default(false,true)) | ternary(user.domain + ',' + 'www.' + user.domain,'organizr.' + user.domain) }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
      TZ: "{{ tz }}"
    volumes:
      - "/opt/organizr:/config"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - organizr
    purge_networks: yes
    restart_policy: unless-stopped
    state: started

- name: Wait for Organizr.css to be created
  wait_for:
    path: "/opt/organizr/www/organizr/css/themes/Organizr.css"
    state: present

- name: Download Gilbn Plex Theme
  get_url:
    url:  "https://raw.githubusercontent.com/gilbN/theme.park/master/CSS/themes/plex/plex-base.css"
    dest: "/opt/organizr/www/organizr/css/themes/"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664
    force: yes
    validate_certs: no
  ignore_errors: yes

- name: Download Gilbn AquaMarine Theme
  get_url:
    url:  "https://raw.githubusercontent.com/gilbN/theme.park/master/CSS/themes/plex/aquamarine.css"
    dest: "/opt/organizr/www/organizr/css/themes/"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664
    force: yes
    validate_certs: no
  ignore_errors: yes

- name: Download Gilbn Dark Theme
  get_url:
    url:  "https://raw.githubusercontent.com/gilbN/theme.park/master/CSS/themes/plex/dark.css"
    dest: "/opt/organizr/www/organizr/css/themes/"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664
    force: yes
    validate_certs: no
  ignore_errors: yes

- name: Download Gilbn Hotline Theme
  get_url:
    url:  "https://github.com/gilbN/theme.park/blob/master/CSS/themes/plex/hotline.css"
    dest: "/opt/organizr/www/organizr/css/themes/"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664
    force: yes
    validate_certs: no
  ignore_errors: yes

- name: Download Gilbn Organizr Dark Theme
  get_url:
    url:  "https://github.com/gilbN/theme.park/blob/master/CSS/themes/plex/organizr-dark.css"
    dest: "/opt/organizr/www/organizr/css/themes/"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664
    force: yes
    validate_certs: no
  ignore_errors: yes

- name: Download Gilbn Space Grey Theme
  get_url:
    url:  "https://github.com/gilbN/theme.park/blob/master/CSS/themes/plex/space-gray.css"
    dest: "/opt/organizr/www/organizr/css/themes/"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664
    force: yes
    validate_certs: no
  ignore_errors: yes

- name: Download Burry Plex Theme
  get_url: 
    url: "https://raw.githubusercontent.com/Burry/organizr-v2-plex-theme/master/css/Plex.css"
    dest: "/opt/organizr/www/organizr/css/themes/"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664
    force: yes
    validate_certs: no
  ignore_errors: yes
