#########################################################################
# Title:         Cloudbox: yyq Role                                     #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Install common packages
  apt:
    state: present
    name:
      - curl
      - jq

- name: Install yyq
  get_url:
    url:  "https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64"
    dest: /usr/local/bin/yyq
    mode: 0775
    owner: root
    group: root
    force: yes
    validate_certs: no
  ignore_errors: yes
  register: x

- name: "Get yyq version"
  shell: "/usr/local/bin/yyq --version | head -n 1 | awk '{ print $3 }'"
  register: yyq_version
  ignore_errors: yes
  when: x is success

- name: "Display yyq version"
  debug:
    msg: "yyq {{ yyq_version.stdout }} installed."
  when: x is success

- debug:
    msg: "yyq install failed."
  when: x is not success
